import "./globals.css";
import { ClusterProvider } from "@/components/cluster/cluster-data-access";
import { ReactQueryProvider } from "./react-query-provider";
import { WalletConnectionProvider } from "@/components/context/WalletConnection";
import { WalletAdapterNetwork } from "@solana/wallet-adapter-base";
import Header from "@/components/header";

export const metadata = {
  title: "senkyo-solana-dapp",
  description: "Generated by create-solana-dapp",
};

const links: { label: string; path: string }[] = [
  { label: "Account", path: "/account" },
  { label: "Clusters", path: "/clusters" },
  { label: "Basic Program", path: "/basic" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            {/* <SolanaProvider> */}
            <WalletConnectionProvider network={WalletAdapterNetwork.Devnet}>
              <Header />
              {children}
            </WalletConnectionProvider>
            {/* </SolanaProvider> */}
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
